[workspace]
resolver = "2"

members = [
    "lib",
    "examples/cli",
    "examples/azure_function",
    "examples/keda-blob-storage",
]

[workspace.dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
azure_core = "0.30.1"
azure_identity = "0.30.0"
env_logger = "0.11.8"
log = "0.4.29"
tokio = { version = "1.49.0", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "macros",
    "io-util",
] }
