[workspace]
resolver = "2"

members = [
    "lib",
    "examples/cli",
    "examples/azure_function",
    "examples/keda-blob-storage",
]

[workspace.dependencies]
anyhow = { version = "1.0.101", features = ["backtrace"] }
azure_core = "0.31.0"
azure_identity = "0.31.0"
env_logger = "0.11.8"
log = "0.4.29"
tokio = { version = "1.49.0", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "macros",
    "io-util",
] }
c2pa = { version = "0.75.19", features = [
    "pdf",
    "add_thumbnails",
    "file_io",
    "fetch_remote_manifests",
    "rust_native_crypto",
], default-features = false }
