[workspace]
resolver = "2"

members = [
  "lib",
  "examples/cli",
  "examples/azure_function",
  "examples/keda-blob-storage"
]

[workspace.dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
azure_core = "0.29.1"
azure_identity = "0.29.0"
env_logger = "0.11.8"
log = "0.4.28"
tokio = { version = "1.48.0", features= ["rt", "rt-multi-thread", "macros"] }
